### PR TITLE
Update cratedb_rag_customer_support_langchain.ipynb

### PR DESCRIPTION
**Pull request by marijaselakovic**
## Summary of the changes / Why this is an improvement
- Update the setup with the absolute path for the requirements
- Update launcher for the Google Colab file

## Checklist

 - [ ] Link to issue this PR refers to (if applicable): 
 - [ ] [CLA](https://crate.io/community/contribute/cla/) is signed

### CODE REVIEW

**Comment by marijaselakovic** [comment]
It is also very important to resolve the dependencies, as reported: https://github.com/crate/cratedb-examples/issues/302

**Comment by marijaselakovic** [comment]
Not really sure why the checks fail now. @amotl can you take a look?

**Comment by amotl** [comment]
## Problem
```python
ValidationError: 1 validation error for OpenAIEmbeddings
__root__
  Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass `openai_api_key` as a named parameter. (type=value_error)
ValidationError: 1 validation error for OpenAIEmbeddings
```
-- https://github.com/crate/cratedb-examples/actions/runs/7918438966/job/21616849498?pr=303#step:6:1382

## Reason
This error is caused because you submitted the pull request from a **personal** repository fork, so the corresponding CI run does not have access to the secrets provided to the CI runner through GitHub. This is why the program is not able to access `OPENAI_API_KEY`, i.e. it is empty.

## Solution
Please hand in your pull request from a branch of a **direct clone of this repository**, instead of from your fork.
```
git clone git@github.com:crate/cratedb-examples.git
```

**Comment by marijaselakovic** [comment]
All changes in: https://github.com/crate/cratedb-examples/pull/310

**Pull request closed without merging**
